# Generated by Django 3.0.5 on 2020-07-28 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_role', to='auth.Group'),
        ),
    ]
