# Generated by Django 3.0.5 on 2020-08-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='needs_updating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='needs_updating',
            field=models.BooleanField(default=False),
        ),
    ]
