# Generated by Django 3.0.5 on 2020-08-09 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200808_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='active_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='active_role',
        ),
    ]
