# Generated by Django 3.1.2 on 2021-01-17 05:00

from django.db import migrations
from phonenumber_field.modelfields import PhoneNumberField


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201114_1258'),
    ]

    operations = [
        # first, rename "phone" to "phone_old". We will retain this data
        # and use the shell to copy the data into the new "phone" parameter
        # which will be more structured
        migrations.RenameField(
            model_name='historicaluser',
            old_name='phone',
            new_name='phone_old',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_old',
        ),

        # now create a new PhoneNumberField named phone that's just empty.
        migrations.AddField(
            model_name='historicaluser',
            name='phone',
            field=PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
