# Generated by Django 3.1.2 on 2021-07-14 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201114_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name'], 'permissions': [('view_clinic_datadashboard', 'Can view clinic data dashboard')]},
        ),
    ]
