# Generated by Django 3.1.2 on 2021-06-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201114_1258'),
        ('users', '0005_auto_20201130_1353'),
    ]

    operations = [
    ]
