# Generated by Django 3.1.2 on 2021-07-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20210626_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name'], 'permissions': [('view_clinic_datadashboard', 'Can view clinic data dashboard')]},
        ),
    ]
