# Generated by Django 2.2.12 on 2020-05-05 15:32

import appointment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pttrack', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAppointment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('written_datetime', models.DateTimeField(blank=True, editable=False)),
                ('last_modified', models.DateTimeField(blank=True, editable=False)),
                ('clindate', models.DateField(verbose_name='Appointment Date')),
                ('clintime', models.TimeField(default=appointment.models.generate_default_appointment_time, verbose_name='Time of Appointment')),
                ('appointment_type', models.CharField(choices=[('PSYCH_NIGHT', 'Psych Night'), ('ACUTE_FOLLOWUP', 'Acute Followup'), ('CHRONIC_CARE', 'Chronic Care'), ('VACCINE', 'Vaccine Followup')], default='CHRONIC_CARE', max_length=15, verbose_name='Appointment Type')),
                ('comment', models.TextField(help_text='What should happen at this appointment?')),
                ('pt_showed', models.NullBooleanField(help_text='Did the patient come to this appointment?', verbose_name='Patient Showed')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pttrack.Provider')),
                ('author_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pttrack.ProviderType')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pttrack.Patient')),
            ],
            options={
                'verbose_name': 'historical appointment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('clindate', models.DateField(verbose_name='Appointment Date')),
                ('clintime', models.TimeField(default=appointment.models.generate_default_appointment_time, verbose_name='Time of Appointment')),
                ('appointment_type', models.CharField(choices=[('PSYCH_NIGHT', 'Psych Night'), ('ACUTE_FOLLOWUP', 'Acute Followup'), ('CHRONIC_CARE', 'Chronic Care'), ('VACCINE', 'Vaccine Followup')], default='CHRONIC_CARE', max_length=15, verbose_name='Appointment Type')),
                ('comment', models.TextField(help_text='What should happen at this appointment?')),
                ('pt_showed', models.NullBooleanField(help_text='Did the patient come to this appointment?', verbose_name='Patient Showed')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pttrack.Provider')),
                ('author_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pttrack.ProviderType')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pttrack.Patient')),
            ],
            options={
                'ordering': ['-clindate', '-clintime'],
            },
        ),
    ]
