# Generated by Django 3.0.5 on 2020-05-10 04:15

from django.db import migrations, models
import osler.appointment.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('clindate', models.DateField(verbose_name='Appointment Date')),
                ('clintime', models.TimeField(default=osler.appointment.models.generate_default_appointment_time, verbose_name='Time of Appointment')),
                ('appointment_type', models.CharField(choices=[('PSYCH_NIGHT', 'Psych Night'), ('ACUTE_FOLLOWUP', 'Acute Followup'), ('CHRONIC_CARE', 'Chronic Care'), ('VACCINE', 'Vaccine Followup')], default='CHRONIC_CARE', max_length=15, verbose_name='Appointment Type')),
                ('comment', models.TextField(help_text='What should happen at this appointment?')),
                ('pt_showed', models.NullBooleanField(help_text='Did the patient come to this appointment?', verbose_name='Patient Showed')),
            ],
            options={
                'ordering': ['-clindate', '-clintime'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAppointment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('written_datetime', models.DateTimeField(blank=True, editable=False)),
                ('last_modified', models.DateTimeField(blank=True, editable=False)),
                ('clindate', models.DateField(verbose_name='Appointment Date')),
                ('clintime', models.TimeField(default=osler.appointment.models.generate_default_appointment_time, verbose_name='Time of Appointment')),
                ('appointment_type', models.CharField(choices=[('PSYCH_NIGHT', 'Psych Night'), ('ACUTE_FOLLOWUP', 'Acute Followup'), ('CHRONIC_CARE', 'Chronic Care'), ('VACCINE', 'Vaccine Followup')], default='CHRONIC_CARE', max_length=15, verbose_name='Appointment Type')),
                ('comment', models.TextField(help_text='What should happen at this appointment?')),
                ('pt_showed', models.NullBooleanField(help_text='Did the patient come to this appointment?', verbose_name='Patient Showed')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical appointment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
