# Generated by Django 3.1.2 on 2020-12-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20201019_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pt_showed',
            field=models.NullBooleanField(help_text='Did the patient come to this appointment?', verbose_name='Patient Showed'),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='pt_showed',
            field=models.NullBooleanField(help_text='Did the patient come to this appointment?', verbose_name='Patient Showed'),
        ),
    ]
