# Generated by Django 3.0.5 on 2020-06-28 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'drug categories',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MeasuringUnit',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dose', models.FloatField(blank=True, null=True)),
                ('stock', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='MM/DD/YYYY', null=True)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.DrugCategory')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Manufacturer')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.MeasuringUnit')),
            ],
        ),
    ]
