# Generated by Django 3.0.5 on 2020-08-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispensehistory',
            old_name='name',
            new_name='drug',
        ),
        migrations.AlterField(
            model_name='drug',
            name='stock',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
