# Generated by Django 3.0.5 on 2020-09-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['name'], 'permissions': [('export_csv', 'Can export drug inventory')]},
        ),
    ]
