# Generated by Django 3.0.5 on 2020-09-09 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200908_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['name'], 'permissions': [('export_csv', 'Can export drug inventory')]},
        ),
    ]
