# Generated by Django 3.0.5 on 2020-08-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200830_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispensehistory',
            options={'verbose_name_plural': 'dispense history'},
        ),
    ]
