# Generated by Django 3.0.5 on 2020-08-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200827_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='drugcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'drug categories'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='measuringunit',
            options={'ordering': ['name']},
        ),
    ]
