# Generated by Django 3.1.2 on 2021-01-18 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_verbose_names_20210118_1141'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_auto_20201209_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensehistory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='dispensehistory',
            name='author_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='author type'),
        ),
        migrations.AlterField(
            model_name='dispensehistory',
            name='dispense',
            field=models.PositiveSmallIntegerField(verbose_name='dispense'),
        ),
        migrations.AlterField(
            model_name='dispensehistory',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.drug', verbose_name='drug'),
        ),
        migrations.AlterField(
            model_name='dispensehistory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='dispensehistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.patient', verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='dispensehistory',
            name='written_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='written_datetime'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.drugcategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='dose',
            field=models.FloatField(verbose_name='dose'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='expiration_date',
            field=models.DateField(help_text='MM/DD/YYYY', verbose_name='exspiration date'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='lot_number',
            field=models.CharField(max_length=100, verbose_name='lot number'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.manufacturer', verbose_name='manufacturer'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='stock',
            field=models.PositiveSmallIntegerField(verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.measuringunit', verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.drugcategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='dose',
            field=models.FloatField(verbose_name='dose'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='expiration_date',
            field=models.DateField(help_text='MM/DD/YYYY', verbose_name='exspiration date'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='lot_number',
            field=models.CharField(max_length=100, verbose_name='lot number'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.manufacturer', verbose_name='manufacturer'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='stock',
            field=models.PositiveSmallIntegerField(verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.measuringunit', verbose_name='unit'),
        ),
    ]
