# Generated by Django 3.1.2 on 2021-04-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_verbose_name_20210118_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='expiration_date',
            field=models.DateField(help_text='MM/DD/YYYY', verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='expiration_date',
            field=models.DateField(help_text='MM/DD/YYYY', verbose_name='expiration date'),
        ),
    ]
