# Generated by Django 3.0.5 on 2020-05-10 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='associated_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provider',
            name='clinical_roles',
            field=models.ManyToManyField(to='core.ProviderType'),
        ),
        migrations.AddField(
            model_name='provider',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Gender'),
        ),
        migrations.AddField(
            model_name='provider',
            name='languages',
            field=models.ManyToManyField(help_text='Specify here languages that are spoken at a level sufficient to be used for medical communication.', to='core.Language'),
        ),
        migrations.AddField(
            model_name='patient',
            name='case_managers',
            field=models.ManyToManyField(to='core.Provider'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnicities',
            field=models.ManyToManyField(to='core.Ethnicity'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Gender'),
        ),
        migrations.AddField(
            model_name='patient',
            name='languages',
            field=models.ManyToManyField(help_text='Specify here languages that are spoken at a level sufficient to be used for medical communication.', to='core.Language'),
        ),
        migrations.AddField(
            model_name='patient',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Outcome'),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_contact_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ContactMethod'),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='associated_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='gender',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Gender'),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='gender',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Gender'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='outcome',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Outcome'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='preferred_contact_method',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ContactMethod'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Provider'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='author_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ProviderType'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='document_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.DocumentType'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Patient'),
        ),
        migrations.AddField(
            model_name='historicalactionitem',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Provider'),
        ),
        migrations.AddField(
            model_name='historicalactionitem',
            name='author_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ProviderType'),
        ),
        migrations.AddField(
            model_name='historicalactionitem',
            name='completion_author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Provider'),
        ),
        migrations.AddField(
            model_name='historicalactionitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalactionitem',
            name='instruction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ActionInstruction'),
        ),
        migrations.AddField(
            model_name='historicalactionitem',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Patient'),
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Provider'),
        ),
        migrations.AddField(
            model_name='document',
            name='author_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ProviderType'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.DocumentType'),
        ),
        migrations.AddField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Provider'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='author_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ProviderType'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='completion_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_actionitem_completed', to='core.Provider'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ActionInstruction'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient'),
        ),
    ]
