# Generated by Django 3.0.5 on 2020-06-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200509_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionitem',
            options={},
        ),
    ]
