# Generated by Django 3.0.5 on 2020-07-22 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200509_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='associated_user',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='clinical_roles',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='languages',
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('can_case_manage', 'Can act as a case manager.')]},
        ),
        migrations.RenameField(
            model_name='gender',
            old_name='long_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='author_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='completion_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_actionitem_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='author_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='historicalactionitem',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalactionitem',
            name='author_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='historicalactionitem',
            name='completion_author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='author_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='state',
            field=models.CharField(default='MO', max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='case_managers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(default='MO', max_length=3),
        ),
        migrations.DeleteModel(
            name='HistoricalProvider',
        ),
    ]
