# Generated by Django 3.0.5 on 2020-07-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20200722_1457'),
        ('followup', '0004_auto_20200722_1457'),
        ('workup', '0002_auto_20200722_1457'),
        ('audit', '0004_auto_20200722_1457'),
        ('core', '0003_auto_20200722_1457'),
        ('appointment', '0004_auto_20200722_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='ProviderType',
        ),
    ]
