# Generated by Django 3.0.5 on 2020-09-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200822_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDataSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Workup Summary',
                'verbose_name_plural': 'Workups Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.patient',),
        ),
    ]
