# Generated by Django 3.0.5 on 2020-09-09 23:31

from django.db import migrations, models
import osler.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200822_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='state',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='zip_code',
            field=models.CharField(default='', max_length=5, validators=[osler.core.validators.validate_zip]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(default='', max_length=5, validators=[osler.core.validators.validate_zip]),
        ),
    ]
