# Generated by Django 3.0.5 on 2020-08-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('case_manage_Patient', 'Can act as a case manager.')]},
        ),
    ]
