# Generated by Django 3.1.2 on 2020-11-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200909_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name'], 'permissions': [('case_manage_Patient', 'Can act as a case manager.'), ('activate_Patient', 'Can in/activate patients')]},
        ),
    ]
