# Generated by Django 3.0.5 on 2020-09-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patientdatasummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdatasummary',
            options={'verbose_name': 'Patient Data Dashboard', 'verbose_name_plural': 'Patient Data Dashboard'},
        ),
    ]
