# Generated by Django 3.0.5 on 2020-08-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200810_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('case_manage_Patient', 'Can act as a case manager.'), ('activate_Patient', 'Can in/activate patients')]},
        ),
    ]
