# Generated by Django 3.0.5 on 2020-09-11 01:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200909_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientDataSummary',
        ),
        migrations.CreateModel(
            name='PatientDataSummary',
            fields=[
                ('patient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Patient')),
                ('bp_readings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': 'Patient Data Dashboard',
                'verbose_name_plural': 'Patient Data Dashboard',
            },
            bases=('core.patient',),
        ),
        migrations.AlterField(
            model_name='Document',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient'),
        ),
        migrations.AlterField(
            model_name='ActionItem',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient'),
        ),
    ]
