# Generated by Django 3.1.2 on 2020-12-04 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0006_auto_20201114_1735'),
        ('core', '0005_auto_20201114_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterStatus',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('clinic_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workup.clinicdate')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.patient')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.encounterstatus')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
