# Generated by Django 3.0.5 on 2020-08-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200728_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('can_case_manage_Patient', 'Can act as a case manager.')]},
        ),
    ]
