# Generated by Django 3.1.2 on 2020-12-22 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import osler.core.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20201114_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='completion_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_actionitem_completed', to=settings.AUTH_USER_MODEL, verbose_name='completion author'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completion date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='historicalactionitem',
            name='completion_author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='completion author'),
        ),
        migrations.AlterField(
            model_name='historicalactionitem',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completion date'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='address',
            field=models.CharField(max_length=200, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='alternate_phone_1',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone 1'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='alternate_phone_1_owner',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone owner 1'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='alternate_phone_2',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone 2'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='alternate_phone_2_owner',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone owner 2'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='alternate_phone_3',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone 3'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='alternate_phone_3_owner',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone owner 3'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='alternate_phone_4',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone 4'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='alternate_phone_4_owner',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone owner 4'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='city',
            field=models.CharField(default='St. Louis', max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='country',
            field=models.CharField(default='USA', max_length=100, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='date_of_birth',
            field=models.DateField(help_text='MM/DD/YYYY', validators=[osler.core.validators.validate_birth_date], verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='first_name',
            field=models.CharField(max_length=100, validators=[osler.core.validators.validate_name], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='gender',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.gender', verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='last_name',
            field=models.CharField(max_length=100, validators=[osler.core.validators.validate_name], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, validators=[osler.core.validators.validate_name], verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='needs_workup',
            field=models.BooleanField(default=True, verbose_name='needs workup'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='outcome',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.outcome', verbose_name='outcome'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='patient_comfortable_with_english',
            field=models.BooleanField(default=True, verbose_name='patient comfortable with english'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='pcp_preferred_zip',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[osler.core.validators.validate_zip], verbose_name='pcp preferred zip'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='preferred_contact_method',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contactmethod', verbose_name='preferred cotact method'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='state',
            field=models.CharField(default='MO', max_length=2, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[osler.core.validators.validate_zip], verbose_name='zip code'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=200, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alternate_phone_1',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone 1'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alternate_phone_1_owner',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone owner 1'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alternate_phone_2',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone 2'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alternate_phone_2_owner',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone owner 2'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alternate_phone_3',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone 3'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alternate_phone_3_owner',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone owner 3'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alternate_phone_4',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone 4'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alternate_phone_4_owner',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='alternate phone owner 4'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(default='St. Louis', max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='country',
            field=models.CharField(default='USA', max_length=100, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(help_text='MM/DD/YYYY', validators=[osler.core.validators.validate_birth_date], verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ethnicities',
            field=models.ManyToManyField(to='core.Ethnicity', verbose_name='ethnicities'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=100, validators=[osler.core.validators.validate_name], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.gender', verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='languages',
            field=models.ManyToManyField(help_text='Specify here languages that are spoken at a level sufficient to be used for medical communication.', to='core.Language', verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=100, validators=[osler.core.validators.validate_name], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, validators=[osler.core.validators.validate_name], verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='needs_workup',
            field=models.BooleanField(default=True, verbose_name='needs workup'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.outcome', verbose_name='outcome'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_comfortable_with_english',
            field=models.BooleanField(default=True, verbose_name='patient comfortable with english'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pcp_preferred_zip',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[osler.core.validators.validate_zip], verbose_name='pcp preferred zip'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='preferred_contact_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.contactmethod', verbose_name='preferred cotact method'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(default='MO', max_length=2, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[osler.core.validators.validate_zip], verbose_name='zip code'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.gender', verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='languages',
            field=models.ManyToManyField(help_text='Specify here languages that are spoken at a level sufficient to be used for medical communication.', to='core.Language', verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, validators=[osler.core.validators.validate_name], verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='phone'),
        ),
    ]
