# Generated by Django 3.0.5 on 2020-08-22 07:39

from django.db import migrations, models
import osler.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200813_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='city',
            field=models.CharField(default='Kansas City', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='zip_code',
            field=models.CharField(default='64106', max_length=5, validators=[osler.core.validators.validate_zip]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(default='Kansas City', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(default='64106', max_length=5, validators=[osler.core.validators.validate_zip]),
        ),
    ]
