# Generated by Django 3.1.2 on 2020-12-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_encounter_encounterstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatient',
            name='needs_workup',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='needs_workup',
        ),
    ]
