# Generated by Django 3.0.5 on 2020-09-11 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0003_auto_20200910_2022'),
        ('workup', '0003_auto_20200910_2022'),
        ('demographics', '0004_auto_20200910_2022'),
        ('inventory', '0003_auto_20200910_2022'),
        ('labs', '0002_auto_20200910_2022'),
        ('appointment', '0003_auto_20200910_2022'),
        ('vaccine', '0002_auto_20200910_2022'),
        ('referral', '0003_auto_20200910_2022'),
        ('core', '0006_auto_20200910_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientDataSummary',
        ),
        migrations.CreateModel(
            name='PatientDataSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Patient Data Dashboard',
                'verbose_name_plural': 'Patient Data Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.patient',),
        ),
    ]
