# Generated by Django 3.0.5 on 2020-10-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200910_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientDataSummary',
        ),
    ]
