# Generated by Django 3.1.2 on 2021-11-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_verbose_name_20210118_1256'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient'], name='core_encoun_patient_24a792_idx'),
        ),
    ]
