# Generated by Django 3.1.2 on 2021-01-17 04:58

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_verbose_name_20210118_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number_set', to='core.patient')),
            ],
            options={
                'unique_together': {('patient', 'description'), ('patient', 'phone_number')},
            },
        ),
    ]
