version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  
services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: osler_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:delegated
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.umkc
    ports:
      - "8000:8000"
    command: /start
    links:
      - selenium

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: osler_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:cached
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  selenium:
    image: selenium/standalone-chrome-debug:3.141
    ports:
      - 4444:4444   # Selenium
      - 5900:5900   # VNC server
