# Generated by Django 3.0.5 on 2020-08-06 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20200806_1411'),
        ('auth', '0011_update_proxy_permissions'),
        ('followup', '0002_auto_20200806_1411'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineActionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(help_text='MM/DD/YYYY')),
                ('comments', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('author_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
                ('completion_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vaccine_vaccineactionitem_completed', to=settings.AUTH_USER_MODEL)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ActionInstruction')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccineSeriesType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('author_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
                ('kind', models.ForeignKey(help_text='What kind of vaccine are you administering?', on_delete=django.db.models.deletion.PROTECT, to='vaccine.VaccineSeriesType')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient')),
            ],
            options={
                'ordering': ['-written_datetime', '-last_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccineFollowup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('subsq_dose', models.BooleanField(verbose_name='Has the patient committed to coming back for another dose?')),
                ('dose_date', models.DateField(blank=True, help_text='When does the patient want to get their next dose (if applicable)?', null=True)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.VaccineActionItem')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('author_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
                ('contact_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ContactMethod')),
                ('contact_resolution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='followup.ContactResult')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccineDoseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from_first', models.DurationField(default=0, help_text='Example: 60 days for 2 months, input minimum required interval')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.VaccineSeriesType')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineDose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('author_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient')),
                ('series', models.ForeignKey(help_text='Which vaccine is this?', on_delete=django.db.models.deletion.CASCADE, to='vaccine.VaccineSeries')),
                ('which_dose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaccine.VaccineDoseType')),
            ],
            options={
                'ordering': ['-written_datetime', '-last_modified'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vaccineactionitem',
            name='vaccine',
            field=models.ForeignKey(help_text='Which vaccine is this for?', on_delete=django.db.models.deletion.CASCADE, to='vaccine.VaccineSeries'),
        ),
    ]
