# Generated by Django 3.1.2 on 2020-12-04 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_encounter_encounterstatus'),
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinedose',
            name='encounter',
            field=models.ForeignKey(null=True,on_delete=django.db.models.deletion.CASCADE, to='core.encounter'),
        ),
    ]
