# Generated by Django 3.0.5 on 2020-06-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200612_1103'),
        ('followup', '0003_auto_20200509_2315'),
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineActionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(help_text='MM/DD/YYYY')),
                ('comments', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Provider')),
                ('author_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ProviderType')),
                ('completion_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vaccine_vaccineactionitem_completed', to='core.Provider')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ActionInstruction')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient')),
                ('vaccine', models.ForeignKey(help_text='Which vaccine is this for?', on_delete=django.db.models.deletion.CASCADE, to='vaccine.VaccineSeries')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccineFollowup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('subsq_dose', models.BooleanField(verbose_name='Has the patient committed to coming back for another dose?')),
                ('dose_date', models.DateField(blank=True, help_text='When does the patient want to get their next dose (if applicable)?', null=True)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.VaccineActionItem')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Provider')),
                ('author_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ProviderType')),
                ('contact_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ContactMethod')),
                ('contact_resolution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='followup.ContactResult')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
