# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-27 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pttrack', '0005_simplehistory_add_change_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallocation',
            name='care_availiable',
            field=models.ManyToManyField(to='pttrack.ReferralType'),
        ),
        migrations.AddField(
            model_name='referraltype',
            name='is_fqhc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='completion_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pttrack_actionitem_completed', to='pttrack.Provider'),
        ),
    ]
