# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-01 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pttrack', '0006_referral_additional_fields_20180826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionitem',
            options={'ordering': ['-written_datetime', '-last_modified']},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-written_datetime', '-last_modified']},
        ),
        migrations.AlterModelOptions(
            name='ethnicity',
            options={'verbose_name_plural': 'ethnicities'},
        ),
    ]
