# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-12-01 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pttrack', '0006_referral_additional_fields_20180826'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraltype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
