# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pttrack', '0007_referraltype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioninstruction',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
