# Generated by Django 3.0.5 on 2020-08-19 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0002_auto_20200806_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chroniccondition',
            options={'ordering': ['name']},
        ),
    ]
