# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-09 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0002_historicalrecords_and_nullboolean_20171119_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldemographics',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
