# Generated by Django 3.0.5 on 2020-09-11 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200910_2022'),
        ('demographics', '0003_auto_20200822_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Demographics',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Patient'),
        ),
    ]
