# Generated by Django 3.1.2 on 2020-12-22 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201221_2024'),
        ('demographics', '0004_auto_20200910_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographics',
            name='chronic_conditions',
        ),
        migrations.AddField(
            model_name='demographics',
            name='chronic_condition',
            field=models.ManyToManyField(blank=True, to='demographics.ChronicCondition', verbose_name='Chronic condition'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='annual_income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demographics.incomerange', verbose_name='Annual income'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='currently_employed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Currently employed'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demographics.educationlevel', verbose_name='Education level'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='has_insurance',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has insurance'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='lives_alone',
            field=models.BooleanField(blank=True, null=True, verbose_name='Lives alone'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demographics.transportationoption', verbose_name='Transportation'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='work_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demographics.workstatus', verbose_name='Work status'),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='annual_income',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='demographics.incomerange', verbose_name='Annual income'),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='currently_employed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Currently employed'),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='education_level',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='demographics.educationlevel', verbose_name='Education level'),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='has_insurance',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has insurance'),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='lives_alone',
            field=models.BooleanField(blank=True, null=True, verbose_name='Lives alone'),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='transportation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='demographics.transportationoption', verbose_name='Transportation'),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='work_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='demographics.workstatus', verbose_name='Work status'),
        ),
    ]
