# Generated by Django 3.0.5 on 2020-05-10 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('followup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(help_text='MM/DD/YYYY')),
                ('contact_instructions', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Provider')),
                ('author_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ProviderType')),
                ('completion_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_followuprequest_completed', to='core.Provider')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient')),
            ],
            options={
                'ordering': ['-written_datetime', '-last_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('S', 'Successful'), ('P', 'Pending'), ('U', 'Unsuccessful')], default='P', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Provider')),
                ('author_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ProviderType')),
                ('kind', models.ForeignKey(help_text='The kind of care the patient should recieve at the referral location.', on_delete=django.db.models.deletion.PROTECT, to='core.ReferralType')),
                ('location', models.ManyToManyField(to='core.ReferralLocation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient')),
            ],
            options={
                'ordering': ['-written_datetime', '-last_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('has_appointment', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], help_text='Did the patient make an appointment?', max_length=1, verbose_name='Appointment scheduled?')),
                ('pt_showed', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], help_text='Did the patient show up to the appointment?', max_length=1, null=True, verbose_name='Appointment attended?')),
                ('appointment_location', models.ManyToManyField(blank=True, help_text='Where did the patient make an appointment?', to='core.ReferralLocation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Provider')),
                ('author_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ProviderType')),
                ('contact_method', models.ForeignKey(help_text='What was the method of contact?', on_delete=django.db.models.deletion.PROTECT, to='core.ContactMethod')),
                ('contact_status', models.ForeignKey(help_text='Did you make contact with the patient about this referral?', on_delete=django.db.models.deletion.PROTECT, to='followup.ContactResult')),
                ('followup_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.FollowupRequest')),
                ('no_apt_reason', models.ForeignKey(blank=True, help_text="If the patient didn't make an appointment, why not?", null=True, on_delete=django.db.models.deletion.PROTECT, to='followup.NoAptReason', verbose_name='No appointment reason')),
                ('no_show_reason', models.ForeignKey(blank=True, help_text="If the patient didn't go to the appointment, why not?", null=True, on_delete=django.db.models.deletion.PROTECT, to='followup.NoShowReason')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referral.Referral')),
            ],
            options={
                'ordering': ['-written_datetime', '-last_modified'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='followuprequest',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.Referral'),
        ),
    ]
