# Generated by Django 3.0.5 on 2020-09-11 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200910_2022'),
        ('referral', '0002_auto_20200806_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Referral',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient'),
        ),
        migrations.AlterField(
            model_name='FollowupRequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient'),
        ),
        migrations.AlterField(
            model_name='PatientContact',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient'),
        ),
    ]
