# Generated by Django 3.1.2 on 2020-12-22 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20201221_2024'),
        ('followup', '0004_auto_20201221_2024'),
        ('referral', '0002_auto_20200806_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuprequest',
            name='completion_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_followuprequest_completed', to=settings.AUTH_USER_MODEL, verbose_name='completion author'),
        ),
        migrations.AlterField(
            model_name='followuprequest',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completion date'),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='appointment_location',
            field=models.ManyToManyField(blank=True, help_text='Where did the patient make an appointment?', to='core.ReferralLocation', verbose_name='Appointment location'),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='contact_method',
            field=models.ForeignKey(help_text='What was the method of contact?', on_delete=django.db.models.deletion.PROTECT, to='core.contactmethod', verbose_name='Contact method'),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='contact_status',
            field=models.ForeignKey(help_text='Did you make contact with the patient about this referral?', on_delete=django.db.models.deletion.PROTECT, to='followup.contactresult', verbose_name='Contact status'),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='no_show_reason',
            field=models.ForeignKey(blank=True, help_text="If the patient didn't go to the appointment, why not?", null=True, on_delete=django.db.models.deletion.PROTECT, to='followup.noshowreason', verbose_name='No show reason'),
        ),
    ]
