# Generated by Django 3.1.2 on 2021-01-18 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_verbose_name_20210118_1256'),
        ('followup', '0004_verbose_name_20210118_1256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('referral', '0002_auto_20200806_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuprequest',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='followuprequest',
            name='author_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='author type'),
        ),
        migrations.AlterField(
            model_name='followuprequest',
            name='completion_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_followuprequest_completed', to=settings.AUTH_USER_MODEL, verbose_name='completion author'),
        ),
        migrations.AlterField(
            model_name='followuprequest',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completion date'),
        ),
        migrations.AlterField(
            model_name='followuprequest',
            name='due_date',
            field=models.DateField(help_text='MM/DD/YYYY', verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='followuprequest',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='followuprequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.patient', verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='followuprequest',
            name='written_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='written_datetime'),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='appointment_location',
            field=models.ManyToManyField(blank=True, help_text='Where did the patient make an appointment?', to='core.ReferralLocation', verbose_name='Appointment location'),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='author_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='author type'),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='contact_method',
            field=models.ForeignKey(help_text='What was the method of contact?', on_delete=django.db.models.deletion.PROTECT, to='core.contactmethod', verbose_name='Contact method'),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='contact_status',
            field=models.ForeignKey(help_text='Did you make contact with the patient about this referral?', on_delete=django.db.models.deletion.PROTECT, to='followup.contactresult', verbose_name='Contact status'),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='no_show_reason',
            field=models.ForeignKey(blank=True, help_text="If the patient didn't go to the appointment, why not?", null=True, on_delete=django.db.models.deletion.PROTECT, to='followup.noshowreason', verbose_name='No show reason'),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.patient', verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='written_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='written_datetime'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='author_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='author type'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.patient', verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='written_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='written_datetime'),
        ),
    ]
