# Generated by Django 3.0.5 on 2020-10-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_delete_patientdatasummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDataSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Patient Data Dashboard',
                'verbose_name_plural': 'Patient Data Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.patient',),
        ),
    ]
