# Generated by Django 3.1.2 on 2020-10-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_auto_20200909_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDataSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Patient Data Dashboard',
                'verbose_name_plural': 'Patient Data Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.patient',),
        ),
    ]
