# Generated by Django 3.1.2 on 2020-11-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datadashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientDataSummary',
        ),
    ]
