# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-31 23:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[(b'PSYCH_NIGHT', b'Psych Night'), (b'ACUTE_FOLLOWUP', b'Acute Followup'), (b'CHRONIC_CARE', b'Chronic Care'), (b'VACCINE', b'Vaccine Followup')], default=b'CHRONIC_CARE', max_length=15, verbose_name=b'Appointment Type'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='clintime',
            field=models.TimeField(default=datetime.datetime(2018, 10, 31, 9, 0, tzinfo=utc), verbose_name=b'Time of Appointment'),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='appointment_type',
            field=models.CharField(choices=[(b'PSYCH_NIGHT', b'Psych Night'), (b'ACUTE_FOLLOWUP', b'Acute Followup'), (b'CHRONIC_CARE', b'Chronic Care'), (b'VACCINE', b'Vaccine Followup')], default=b'CHRONIC_CARE', max_length=15, verbose_name=b'Appointment Type'),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='clintime',
            field=models.TimeField(default=datetime.datetime(2018, 10, 31, 9, 0, tzinfo=utc), verbose_name=b'Time of Appointment'),
        ),
    ]
