# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-11-03 19:14
from __future__ import unicode_literals

import appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_vaccineappointment_20181031_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pt_showed',
            field=models.NullBooleanField(help_text=b'Did the patient come to this appointment?', verbose_name=b'Patient Showed'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='pt_showed',
            field=models.NullBooleanField(help_text=b'Did the patient come to this appointment?', verbose_name=b'Patient Showed'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='clintime',
            field=models.TimeField(default=appointment.models.generate_default_appointment_time, verbose_name=b'Time of Appointment'),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='clintime',
            field=models.TimeField(default=appointment.models.generate_default_appointment_time, verbose_name=b'Time of Appointment'),
        ),
    ]
