# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-01 20:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_vaccineappointment_20181031_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-clindate', '-clintime']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='clintime',
            field=models.TimeField(default=datetime.datetime(2018, 12, 1, 9, 0, tzinfo=utc), verbose_name=b'Time of Appointment'),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='clintime',
            field=models.TimeField(default=datetime.datetime(2018, 12, 1, 9, 0, tzinfo=utc), verbose_name=b'Time of Appointment'),
        ),
    ]
