# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-10-21 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcontact',
            name='has_appointment',
            field=models.CharField(blank=True, choices=[(b'Y', b'Yes'), (b'N', b'No')], help_text=b'Did the patient make an appointment?', max_length=1, verbose_name=b'Appointment scheduled?'),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='pt_showed',
            field=models.CharField(blank=True, choices=[(b'Y', b'Yes'), (b'N', b'No')], help_text=b'Did the patient show up to the appointment?', max_length=1, null=True, verbose_name=b'Appointment attended?'),
        ),
    ]
