# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-26 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dose', models.IntegerField()),
                ('total_inventory', models.IntegerField()),
                ('status', models.CharField(default='Out of Stock', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Antibiotics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dose', models.IntegerField()),
                ('total_inventory', models.IntegerField()),
                ('status', models.CharField(default='Out of Stock', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cardiovascular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dose', models.IntegerField()),
                ('total_inventory', models.IntegerField()),
                ('status', models.CharField(default='Out of Stock', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endocrine_and_GI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dose', models.IntegerField()),
                ('total_inventory', models.IntegerField()),
                ('status', models.CharField(default='Out of Stock', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dose', models.IntegerField()),
                ('total_inventory', models.IntegerField()),
                ('status', models.CharField(default='Out of Stock', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pain_Relief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dose', models.IntegerField()),
                ('total_inventory', models.IntegerField()),
                ('status', models.CharField(default='Out of Stock', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Respiratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dose', models.IntegerField()),
                ('total_inventory', models.IntegerField()),
                ('status', models.CharField(default='Out of Stock', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dose', models.IntegerField()),
                ('total_inventory', models.IntegerField()),
                ('status', models.CharField(default='Out of Stock', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
