# Generated by Django 3.1.2 on 2020-12-16 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_auto_20200910_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.TextField(blank=True, verbose_name='HPI')),
                ('route', models.TextField(blank=True, verbose_name='HPI')),
                ('freq', models.TextField(blank=True, verbose_name='HPI')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.drug')),
            ],
        ),
    ]
