# Generated by Django 3.1.2 on 2020-12-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='freq',
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dose',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='route',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
