# Generated by Django 3.1.2 on 2020-12-28 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201114_1258'),
        ('prescriptions', '0003_auto_20201223_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.patient'),
        ),
    ]
