# Generated by Django 3.0.5 on 2020-07-22 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('audit', '0003_pageviewrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageviewrecord',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group'),
        ),
    ]
