# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-01 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0002_simplehistory_add_change_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinictype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='diagnosistype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='progressnote',
            options={'ordering': ['-written_datetime', '-last_modified']},
        ),
        migrations.AlterModelOptions(
            name='workup',
            options={'ordering': ['-written_datetime', '-last_modified']},
        ),
        migrations.RemoveField(
            model_name='clinicdate',
            name='gcal_id',
        ),
        migrations.AlterField(
            model_name='workup',
            name='clinic_day',
            field=models.ForeignKey(help_text=b'When was the patient seen?', on_delete=django.db.models.deletion.CASCADE, to='workup.ClinicDate'),
        ),
    ]
