# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pttrack.validators


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0002_simplehistory_add_change_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkup',
            name='attending',
            field=models.ForeignKey(
                blank=True, db_constraint=False,
                help_text=b'Which attending saw the patient?',
                null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+', to='pttrack.Provider',
                validators=[pttrack.validators.validate_attending]),
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='clinic_day',
            field=models.ForeignKey(
                blank=True, db_constraint=False,
                help_text=b'When was the patient seen?', null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+', to='workup.ClinicDate'),
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='signer',
            field=models.ForeignKey(
                blank=True, db_constraint=False, null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+', to='pttrack.Provider',
                validators=[pttrack.validators.validate_attending]),
        ),
        migrations.AlterField(
            model_name='workup',
            name='clinic_day',
            field=models.ForeignKey(
                help_text=b'When was the patient seen?',
                on_delete=django.db.models.deletion.PROTECT,
                to='workup.ClinicDate'),
        ),
    ]
