# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-03 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0005_set_orderings_and_db_do_nothing_20190902_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicdate',
            name='gcal_id',
        ),
    ]
