# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-08 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0006_remove_clinicdate_gcal_id'),
    ]

    operations = [
        migrations.RenameModel('ProgressNote','PsychNote')
    ]
