# Generated by Django 3.0.5 on 2020-11-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20201019_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('domain',), 'verbose_name': 'site', 'verbose_name_plural': 'sites'},
        ),
    ]
