# Generated by Django 2.1.15 on 2020-05-05 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pttrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicCondition',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('has_insurance', models.BooleanField(blank=True, null=True)),
                ('ER_visit_last_year', models.BooleanField(blank=True, null=True, verbose_name='Visited ER in the Past Year')),
                ('last_date_physician_visit', models.DateField(blank=True, null=True, verbose_name="Date of Patient's Last Visit to Physician or ER")),
                ('lives_alone', models.BooleanField(blank=True, null=True)),
                ('dependents', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of Dependents')),
                ('currently_employed', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDemographics',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('has_insurance', models.BooleanField(blank=True, null=True)),
                ('ER_visit_last_year', models.BooleanField(blank=True, null=True, verbose_name='Visited ER in the Past Year')),
                ('last_date_physician_visit', models.DateField(blank=True, null=True, verbose_name="Date of Patient's Last Visit to Physician or ER")),
                ('lives_alone', models.BooleanField(blank=True, null=True)),
                ('dependents', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of Dependents')),
                ('currently_employed', models.BooleanField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical demographics',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='IncomeRange',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAccess',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Resource accesses',
            },
        ),
        migrations.CreateModel(
            name='TransportationOption',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Work statuses',
            },
        ),
        migrations.AddField(
            model_name='historicaldemographics',
            name='annual_income',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='demographics.IncomeRange'),
        ),
        migrations.AddField(
            model_name='historicaldemographics',
            name='education_level',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='demographics.EducationLevel'),
        ),
        migrations.AddField(
            model_name='historicaldemographics',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldemographics',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pttrack.Patient'),
        ),
        migrations.AddField(
            model_name='historicaldemographics',
            name='transportation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='demographics.TransportationOption'),
        ),
        migrations.AddField(
            model_name='historicaldemographics',
            name='work_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='demographics.WorkStatus'),
        ),
        migrations.AddField(
            model_name='demographics',
            name='annual_income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demographics.IncomeRange'),
        ),
        migrations.AddField(
            model_name='demographics',
            name='chronic_condition',
            field=models.ManyToManyField(blank=True, to='demographics.ChronicCondition'),
        ),
        migrations.AddField(
            model_name='demographics',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demographics.EducationLevel'),
        ),
        migrations.AddField(
            model_name='demographics',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pttrack.Patient'),
        ),
        migrations.AddField(
            model_name='demographics',
            name='resource_access',
            field=models.ManyToManyField(blank=True, to='demographics.ResourceAccess', verbose_name='Access to Resources'),
        ),
        migrations.AddField(
            model_name='demographics',
            name='transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demographics.TransportationOption'),
        ),
        migrations.AddField(
            model_name='demographics',
            name='work_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demographics.WorkStatus'),
        ),
    ]
