# Generated by Django 3.0.5 on 2020-08-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressnote',
            options={'permissions': [('sign_ProgressNote', 'Can sign note')]},
        ),
        migrations.AlterModelOptions(
            name='workup',
            options={'permissions': [('export_pdf_Workup', 'Can export note PDF'), ('sign_Workup', 'Can sign note')]},
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='labs_ordered_quest',
            field=models.TextField(blank=True, null=True, verbose_name='Labs Ordered Externally'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='labs_ordered_quest',
            field=models.TextField(blank=True, null=True, verbose_name='Labs Ordered Externally'),
        ),
    ]
