# Generated by Django 3.0.5 on 2020-07-22 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import osler.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressnote',
            options={'permissions': [('can_sign', 'Can sign note')]},
        ),
        migrations.AlterModelOptions(
            name='workup',
            options={'permissions': [('can_sign', 'Can sign note'), ('can_export_pdf', 'Can export note PDF')]},
        ),
        migrations.AlterField(
            model_name='historicalprogressnote',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalprogressnote',
            name='author_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='historicalprogressnote',
            name='signer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, validators=[osler.core.validators.validate_attending]),
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='attending',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Which attending saw the patient?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, validators=[osler.core.validators.validate_attending]),
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='author_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='signer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, validators=[osler.core.validators.validate_attending]),
        ),
        migrations.AlterField(
            model_name='progressnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progressnote',
            name='author_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='progressnote',
            name='signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_workup_progressnote', to=settings.AUTH_USER_MODEL, validators=[osler.core.validators.validate_attending]),
        ),
        migrations.AlterField(
            model_name='workup',
            name='attending',
            field=models.ForeignKey(blank=True, help_text='Which attending saw the patient?', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attending_physician', to=settings.AUTH_USER_MODEL, validators=[osler.core.validators.validate_attending]),
        ),
        migrations.AlterField(
            model_name='workup',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workup',
            name='author_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='other_volunteer',
            field=models.ManyToManyField(blank=True, help_text='Which other volunteer(s) did you work with (if any)?', related_name='other_volunteer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workup',
            name='signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_workup_workup', to=settings.AUTH_USER_MODEL, validators=[osler.core.validators.validate_attending]),
        ),
    ]
