# Generated by Django 3.0.5 on 2020-08-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressnote',
            options={'permissions': [('sign_ProgressNote', 'Can sign note')]},
        ),
        migrations.AlterModelOptions(
            name='workup',
            options={'permissions': [('export_pdf_Workup', 'Can export note PDF'), ('sign_Workup', 'Can sign note')]},
        ),
    ]
