# Generated by Django 3.0.5 on 2020-07-29 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0002_auto_20200722_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressnote',
            options={'permissions': [('workup.ProgressNote.can_sign', 'Can sign note')]},
        ),
        migrations.AlterModelOptions(
            name='workup',
            options={'permissions': [('workup.Workup.can_export_pdf', 'Can export note PDF'), ('workup.Workup.can_sign', 'Can sign note')]},
        ),
    ]
