# Generated by Django 3.0.5 on 2020-08-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0002_auto_20200810_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkup',
            name='labs_ordered_quest',
            field=models.TextField(blank=True, null=True, verbose_name='Labs Ordered Externally'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='labs_ordered_quest',
            field=models.TextField(blank=True, null=True, verbose_name='Labs Ordered Externally'),
        ),
    ]
