# Generated by Django 3.0.5 on 2020-08-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0003_auto_20200729_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressnote',
            options={'permissions': [('can_sign_ProgressNote', 'Can sign note')]},
        ),
        migrations.AlterModelOptions(
            name='workup',
            options={'permissions': [('can_export_pdf_Workup', 'Can export note PDF'), ('can_sign_Workup', 'Can sign note')]},
        ),
    ]
