# Generated by Django 3.0.5 on 2020-09-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0004_auto_20200921_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkup',
            old_name='pmh_psh',
            new_name='pmh',
        ),
        migrations.RenameField(
            model_name='workup',
            old_name='pmh_psh',
            new_name='pmh',
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='pmh',
            field=models.TextField(blank=True, verbose_name='PMH'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='pmh',
            field=models.TextField(blank=True, verbose_name='PMH'),
        ),
        migrations.AddField(
            model_name='historicalworkup',
            name='psh',
            field=models.TextField(blank=True, verbose_name='PSH'),
        ),
        migrations.AddField(
            model_name='workup',
            name='psh',
            field=models.TextField(blank=True, verbose_name='PSH'),
        ),
    ]
