# Generated by Django 3.0.5 on 2020-09-24 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0005_auto_20200923_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkup',
            old_name='pmh_psh',
            new_name='pmh',
        ),
        migrations.RenameField(
            model_name='workup',
            old_name='pmh_psh',
            new_name='pmh',
        ),
    ]
