# Generated by Django 3.1.2 on 2020-11-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0005_auto_20200923_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkup',
            name='rx',
            field=models.TextField(blank=True, help_text='Ex: Ibuprofen 200mg 1 tab PO PRN Q8H for pain #28', verbose_name='Prescription Orders'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='rx',
            field=models.TextField(blank=True, help_text='Ex: Ibuprofen 200mg 1 tab PO PRN Q8H for pain #28', verbose_name='Prescription Orders'),
        ),
    ]
