# Generated by Django 3.1.2 on 2020-12-11 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200910_1735'),
        ('workup', '0006_auto_20201114_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkup',
            name='meds',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Medications the patient is currently taking', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.drug'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='meds',
            field=models.ForeignKey(blank=True, help_text='Medications the patient is currently taking', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.drug'),
        ),
    ]
