# Generated by Django 3.1.2 on 2020-12-22 02:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201221_2024'),
        ('workup', '0006_auto_20201114_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkup',
            name='clinic_day',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='When was the patient seen?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workup.clinicdate', verbose_name='Clinc day'),
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='got_voucher',
            field=models.BooleanField(default=False, verbose_name='Got voucher'),
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='imaging_voucher_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Imaging voucher'),
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='patient_pays',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Patient pays'),
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='patient_pays_imaging',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Patient pays imaging'),
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='voucher_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Voucher amount'),
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='will_return',
            field=models.BooleanField(default=False, help_text='Will the pt. return to SNHC?', verbose_name='Will return'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='clinic_day',
            field=models.ForeignKey(help_text='When was the patient seen?', on_delete=django.db.models.deletion.PROTECT, to='workup.clinicdate', verbose_name='Clinc day'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='got_voucher',
            field=models.BooleanField(default=False, verbose_name='Got voucher'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='imaging_voucher_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Imaging voucher'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='patient_pays',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Patient pays'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='patient_pays_imaging',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Patient pays imaging'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='referral_location',
            field=models.ManyToManyField(blank=True, to='core.ReferralLocation', verbose_name='Rererral location'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='referral_type',
            field=models.ManyToManyField(blank=True, to='core.ReferralType', verbose_name='Referral type'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='voucher_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Voucher amount'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='will_return',
            field=models.BooleanField(default=False, help_text='Will the pt. return to SNHC?', verbose_name='Will return'),
        ),
    ]
