# Generated by Django 3.0.5 on 2020-09-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0006_auto_20200923_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkup',
            name='psh',
            field=models.TextField(blank=True, verbose_name='PSH'),
        ),
        migrations.AddField(
            model_name='workup',
            name='psh',
            field=models.TextField(blank=True, verbose_name='PSH'),
        ),
        migrations.AlterField(
            model_name='historicalworkup',
            name='pmh',
            field=models.TextField(blank=True, db_column='old_pmh_psh', verbose_name='PMH'),
        ),
        migrations.AlterField(
            model_name='workup',
            name='pmh',
            field=models.TextField(blank=True, db_column='old_pmh_psh', verbose_name='PMH'),
        ),
    ]
