# Generated by Django 3.1.2 on 2020-12-07 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_make_encounters'),
        ('workup', '0007_auto_20201203_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workup',
            options={'ordering': ['-encounter__clinic_day'], 'permissions': [('export_pdf_Workup', 'Can export note PDF'), ('sign_Workup', 'Can sign note')]},
        ),
        migrations.RemoveField(
            model_name='historicalworkup',
            name='clinic_day',
        ),
        migrations.RemoveField(
            model_name='workup',
            name='clinic_day',
        ),
        migrations.DeleteModel(
            name='ClinicDate',
        ),
        migrations.DeleteModel(
            name='ClinicType',
        ),
        migrations.AlterField(
            model_name='workup',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encounter'),
        ),
        migrations.AlterField(
            model_name='basicnote',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encounter'),
        ),
        migrations.AlterField(
            model_name='attestablebasicnote',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encounter'),
        ),
        migrations.RemoveField(
            model_name='historicalworkup',
            name='will_return',
        ),
        migrations.RemoveField(
            model_name='workup',
            name='referral_location',
        ),
        migrations.RemoveField(
            model_name='workup',
            name='referral_type',
        ),
        migrations.RemoveField(
            model_name='workup',
            name='will_return',
        ),
    ]
