# Generated by Django 3.1.2 on 2020-12-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200910_1735'),
        ('workup', '0007_auto_20201210_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkup',
            name='meds',
        ),
        migrations.RemoveField(
            model_name='workup',
            name='meds',
        ),
        migrations.AddField(
            model_name='workup',
            name='meds',
            field=models.ManyToManyField(blank=True, help_text='Medications the patient is currently taking', to='inventory.Drug'),
        ),
    ]
