# Generated by Django 3.1.2 on 2020-12-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200910_1735'),
        ('workup', '0008_auto_20201210_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workup',
            name='meds',
            field=models.ManyToManyField(blank=True, to='inventory.Drug'),
        ),
    ]
