# Generated by Django 3.1.2 on 2021-11-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0009_verbose_name_20210118_1256'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workup',
            index=models.Index(fields=['patient'], name='workup_work_patient_be94d9_idx'),
        ),
    ]
