# Generated by Django 3.2.10 on 2023-02-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workup', '0010_alter_attestablebasicnote_signer_alter_workup_signer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkup',
            name='height',
        ),
        migrations.RemoveField(
            model_name='workup',
            name='height',
        ),
        migrations.AddField(
            model_name='historicalworkup',
            name='height_feet',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height in Feet'),
        ),
        migrations.AddField(
            model_name='historicalworkup',
            name='height_inches',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height in Inches'),
        ),
        migrations.AddField(
            model_name='workup',
            name='height_feet',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height in Feet'),
        ),
        migrations.AddField(
            model_name='workup',
            name='height_inches',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height in Inches'),
        ),
    ]
