# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0003_simplehistory_add_v2_migrations_20190324_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreferralfollowup',
            name='apt_location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pttrack.ReferralLocation'),
        ),
        migrations.AlterField(
            model_name='historicalreferralfollowup',
            name='noapt_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='followup.NoAptReason'),
        ),
        migrations.AlterField(
            model_name='historicalreferralfollowup',
            name='noshow_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='followup.NoShowReason'),
        ),
        migrations.AlterField(
            model_name='historicalreferralfollowup',
            name='referral_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pttrack.ReferralType'),
        ),
    ]
