# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-19 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pttrack', '0009_set_orderings_20190902_2116'),
        ('followup', '0005_db_do_nothings_20190902_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalfollowup',
            name='actionitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pttrack.ActionItem'),
        ),
        migrations.AddField(
            model_name='historicalgeneralfollowup',
            name='actionitem',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pttrack.ActionItem'),
        ),
        migrations.AddField(
            model_name='historicallabfollowup',
            name='actionitem',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pttrack.ActionItem'),
        ),
        migrations.AddField(
            model_name='historicalreferralfollowup',
            name='actionitem',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pttrack.ActionItem'),
        ),
        migrations.AddField(
            model_name='historicalvaccinefollowup',
            name='actionitem',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pttrack.ActionItem'),
        ),
        migrations.AddField(
            model_name='labfollowup',
            name='actionitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pttrack.ActionItem'),
        ),
        migrations.AddField(
            model_name='referralfollowup',
            name='actionitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pttrack.ActionItem'),
        ),
        migrations.AddField(
            model_name='vaccinefollowup',
            name='actionitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pttrack.ActionItem'),
        ),
    ]
