# Generated by Django 3.1.2 on 2020-12-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0002_auto_20200806_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labfollowup',
            name='author',
        ),
        migrations.RemoveField(
            model_name='labfollowup',
            name='author_type',
        ),
        migrations.RemoveField(
            model_name='labfollowup',
            name='contact_method',
        ),
        migrations.RemoveField(
            model_name='labfollowup',
            name='contact_resolution',
        ),
        migrations.RemoveField(
            model_name='labfollowup',
            name='patient',
        ),
        migrations.DeleteModel(
            name='HistoricalLabFollowup',
        ),
        migrations.DeleteModel(
            name='LabFollowup',
        ),
    ]
