# Generated by Django 3.1.2 on 2021-01-18 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_verbose_name_20210118_1256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('followup', '0003_auto_20201202_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitemfollowup',
            name='action_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actionitem', verbose_name='Action item'),
        ),
        migrations.AlterField(
            model_name='actionitemfollowup',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='actionitemfollowup',
            name='author_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='author type'),
        ),
        migrations.AlterField(
            model_name='actionitemfollowup',
            name='contact_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contactmethod', verbose_name='Contact method'),
        ),
        migrations.AlterField(
            model_name='actionitemfollowup',
            name='contact_resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='followup.contactresult', verbose_name='Contact resolution'),
        ),
        migrations.AlterField(
            model_name='actionitemfollowup',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='actionitemfollowup',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.patient', verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='actionitemfollowup',
            name='written_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='written_datetime'),
        ),
        migrations.AlterField(
            model_name='contactresult',
            name='attempt_again',
            field=models.BooleanField(default=False, help_text='True if outcome means the pt should be contacted again.', verbose_name='Attempt again'),
        ),
        migrations.AlterField(
            model_name='contactresult',
            name='patient_reached',
            field=models.BooleanField(default=True, help_text='True if outcome means they reached the patient', verbose_name='Patient reached'),
        ),
        migrations.AlterField(
            model_name='historicalactionitemfollowup',
            name='action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.actionitem', verbose_name='Action item'),
        ),
        migrations.AlterField(
            model_name='historicalactionitemfollowup',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='historicalactionitemfollowup',
            name='author_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group', verbose_name='author type'),
        ),
        migrations.AlterField(
            model_name='historicalactionitemfollowup',
            name='contact_method',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contactmethod', verbose_name='Contact method'),
        ),
        migrations.AlterField(
            model_name='historicalactionitemfollowup',
            name='contact_resolution',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='followup.contactresult', verbose_name='Contact resolution'),
        ),
        migrations.AlterField(
            model_name='historicalactionitemfollowup',
            name='last_modified',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='historicalactionitemfollowup',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.patient', verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='historicalactionitemfollowup',
            name='written_datetime',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='written_datetime'),
        ),
    ]
