#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset




if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
echo $DATABASE_URL

postgres_ready() {
python << END
import sys

import psycopg2

#print("${POSTGRES_DB}")
#print("${POSTGRES_USER}")
#print("${POSTGRES_PASSWORD}")
#print("${POSTGRES_HOST}")
#print("${POSTGRES_PORT}")

try:
    psycopg2.connect(
        dbname="osler",
        user="django",
        password="vT8MiDHe;@N9a7M]TB#GMs8QW3ndusn^",
        host="kc-med-oslerdb.kc.umkc.edu",
        port="5432",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available... '
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
