# Custom settings for umkc deploy
# -----------------------------------------------------------------------------
OSLER_DISPLAY_REFERRALS = False
OSLER_DISPLAY_APPOINTMENTS = False
OSLER_DISPLAY_CASE_MANAGERS = False
OSLER_DISPLAY_ATTESTABLE_BASIC_NOTE = False
OSLER_DISPLAY_DIAGNOSIS = False
OSLER_DISPLAY_VOUCHERS = False
OSLER_DISPLAY_WILL_RETURN = False

OSLER_DEFAULT_CITY = "Kansas City"
OSLER_DEFAULT_STATE = "MO"
OSLER_DEFAULT_ZIP_CODE = "64106"
OSLER_DEFAULT_COUNTRY = "USA"
OSLER_DEFAULT_ADDRESS = "205 East 9th St."
