# Generated by Django 3.0.5 on 2020-08-07 21:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20200806_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-lab_time'],
            },
        ),
        migrations.CreateModel(
            name='LabType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('order_index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='ContinuousMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='labs.Measurement')),
                ('value', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            bases=('labs.measurement',),
        ),
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('long_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=15)),
                ('unit', models.CharField(blank=True, max_length=15, null=True)),
                ('panic_upper', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('panic_lower', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('value_type', models.CharField(choices=[('Continuous', 'Numerical'), ('Discrete', 'Categorical')], max_length=15)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('lab_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labs.LabType')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='measurement',
            name='measurement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labs.MeasurementType'),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labs.LabType'),
        ),
        migrations.AddField(
            model_name='lab',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient'),
        ),
        migrations.CreateModel(
            name='DiscreteResultType',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('is_panic', models.CharField(choices=[('T', 'Abnormal value'), ('F', 'Normal value')], default='T', max_length=1)),
                ('measurement_type', models.ManyToManyField(to='labs.MeasurementType')),
            ],
        ),
        migrations.CreateModel(
            name='DiscreteMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='labs.Measurement')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labs.DiscreteResultType')),
            ],
            bases=('labs.measurement',),
        ),
    ]
