# Generated by Django 3.0.5 on 2020-07-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discreteresulttype',
            name='measurement_type',
            field=models.ManyToManyField(to='labs.MeasurementType'),
        ),
    ]
