# Generated by Django 3.0.5 on 2020-10-01 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuousmeasurementtype',
            name='display_decimals',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='continuousmeasurement',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='continuousmeasurementtype',
            name='panic_lower',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='All labs below this value will display as blue with a warning sign. Will also be used as the lower bound of reference.', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='continuousmeasurementtype',
            name='panic_upper',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='All labs above this value will display as red with a warning sign. Will also be used as the upper bound of reference.', max_digits=7, null=True),
        ),
    ]
