# Generated by Django 3.0.5 on 2020-08-22 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscreteMeasurementType',
            fields=[
                ('long_name', models.CharField(help_text='A unique name of the measurement', max_length=30, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=30)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Order at which this measurement will display')),
                ('lab_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labs.LabType')),
            ],
            options={
                'ordering': ['order_index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContinuousMeasurementType',
            fields=[
                ('long_name', models.CharField(help_text='A unique name of the measurement', max_length=30, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=30)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Order at which this measurement will display')),
                ('unit', models.CharField(blank=True, max_length=15, null=True)),
                ('panic_upper', models.DecimalField(blank=True, decimal_places=1, help_text='All labs above this value will display as red with a warning sign. Will also be used as the upper bound of reference.', max_digits=5, null=True)),
                ('panic_lower', models.DecimalField(blank=True, decimal_places=1, help_text='All labs below this value will display as blue with a warning sign. Will also be used as the lower bound of reference.', max_digits=5, null=True)),
                ('lab_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labs.LabType')),
            ],
            options={
                'ordering': ['order_index'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='continuousmeasurement',
            name='measurement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labs.ContinuousMeasurementType'),
        ),
        migrations.AlterField(
            model_name='discretemeasurement',
            name='measurement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labs.DiscreteMeasurementType'),
        ),
        migrations.AlterField(
            model_name='discreteresulttype',
            name='measurement_type',
            field=models.ManyToManyField(to='labs.DiscreteMeasurementType'),
        ),
        migrations.DeleteModel(
            name='MeasurementType',
        ),
    ]
