# Generated by Django 3.1.2 on 2020-12-04 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_encounter_encounterstatus'),
        ('labs', '0002_auto_20201001_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.encounter'),
        ),
    ]
