# Generated by Django 3.0.5 on 2020-07-23 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_discreteresulttype_measurement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='written_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
