# Generated by Django 3.0.5 on 2020-07-23 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_auto_20200723_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lab_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lab',
            name='written_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
