# Generated by Django 3.0.5 on 2020-07-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_auto_20200723_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='lab_datetime',
            new_name='lab_time',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='written_datetime',
        ),
    ]
