# Generated by Django 3.0.5 on 2020-08-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_auto_20200723_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementtype',
            name='value_type',
            field=models.CharField(choices=[('Continuous', 'Numerical'), ('Discrete', 'Categorical')], default='Continuous', max_length=15),
            preserve_default=False,
        ),
    ]
