# Generated by Django 3.0.5 on 2020-08-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_measurementtype_value_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'ordering': ['-lab_time']},
        ),
        migrations.AddField(
            model_name='measurement',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
