# Generated by Django 3.0.5 on 2020-08-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_auto_20200806_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='order_index',
        ),
        migrations.AddField(
            model_name='measurementtype',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
