# Generated by Django 3.0.5 on 2020-08-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0008_auto_20200806_0303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtype',
            options={'ordering': ['order_index']},
        ),
        migrations.AlterModelOptions(
            name='measurementtype',
            options={'ordering': ['order_index']},
        ),
        migrations.AddField(
            model_name='labtype',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
